# stages:
#   - build
#   - lint

# build_project:
#   stage: build
#   script:
#     - xcodebuild clean -project IOS-MovieRecommendation.xcodeproj -scheme SchemeName | xcpretty
#     - xcodebuild test -project IOS-MovieRecommendation.xcodeproj -scheme SchemeName -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' | xcpretty -s
#   tags:
#     - ios_11-3
#     - xcode_9-3
#     - macos_10-13

linter:
  stage: linter
  image: ubuntu
  script:
    - chmod +x mvnw
    - ./mvnw spotbugs:spotbugs
  dependencies:
    - build

stages:
  - linter

variables:
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"

before_script:
  - sudo gem install bundler && bundle update

lint:
  tags:
    - ios
  stage: lint
  script:
    - bundle exec fastlane lint
  only:
    - branches
  except:
    - tags
  artifacts:
    paths:
      - fastlane/swiftlint.html
  allow_failure: false